server:
 port:  9090
spring:
 application:
  name: crudoperations
 datasource:
  url: ${DB_URI:jdbc:mysql://localhost:3306/crud?serverTimezone=UTC}&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:}
